### ISSUE TITLE
jest_test should also create a run target to update snapshots

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_jest#17]
For example, with `jest_test(name = "test", ...)`, I should be able to run `bazel run :test/update` (exact naming convention TBD) to trigger the appropriate `jest --updateSnapshot` command and then copy the updated snapshots back into the source tree using [your technique](https://www.aspect.dev/blog/bazel-can-write-to-the-source-folder).

**Comment by Kernald** [comment]
Something seem to be at least partially there: https://github.com/aspect-build/rules_jest/blob/main/jest/private/jest-reporter.js

**Comment by gregmagolan** [comment]
> Something seem to be at least partially there: https://github.com/aspect-build/rules_jest/blob/main/jest/private/jest-reporter.js

Looks like that bit came in from rules_nodejs @bazel/jest code that was used at the starting point.

We're working on first class support for snapshot updates soon.

**Comment by gregmagolan** [comment]
Add in https://github.com/aspect-build/rules_jest/commit/1141e1b3c25df89b6563de3a3aa4cde538f19ee7

**Comment by gregmagolan** [comment]
> 

Yeah. That was brought over from rules_nodejs but wasn't wired up yet. Done now with https://github.com/aspect-build/rules_jest/commit/1141e1b3c25df89b6563de3a3aa4cde538f19ee7.

**Comment by gregmagolan** [comment]
@jfirebaugh Let me know how that works for you. The update target is
```
bazel run {name}_update_snapshots
```
