### ISSUE TITLE
[Bug]: jest-cli not found

### ISSUE THREAD

**Issue by niks199** [aspect-build/rules_jest#173]
### What happened?

BUILD:113:10: no such target '//:node_modules/jest-cli': target 'node_modules/jest-cli' not declared in package '' defined by

strange, did everything according to example react-cra. Using WORKSPACE though

### Version

Development (host) and target OS/architectures:
alpine
Output of `bazel --version`:
6.11
Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:

Language(s) and/or frameworks involved:
rules_ts, rules_jest

**Comment by jbedard** [comment]
Is `jest-cli` in your root package.json? If so, can you provide an example repo reproducing the rule?

**Comment by jbedard** [comment]
It would be best to ask support questions somewhere such as the bazel slack. Or checkout the examples here or https://github.com/aspect-build/bazel-examples
