### ISSUE TITLE
Support JUnit XML output / `XML_OUTPUT_FILE`

### ISSUE THREAD

**Issue by jfirebaugh** [aspect-build/rules_jest#25]
The `jest_test` rule should automatically produce JUnit XML output to the file specified by `XML_OUTPUT_FILE`.

The jest example in rules_nodejs does this via [jest-junit](https://www.npmjs.com/package/jest-junit): https://github.com/bazelbuild/rules_nodejs/blob/8f2333cef700d2e94aead34cf710f07580896a68/examples/jest/jest.config.js#L10

**Comment by kormide** [comment]
Fixed in https://github.com/aspect-build/rules_jest/commit/26f979e1999743f269d214326ec57afb63c83f11. Will cut a release shortly.
