### ISSUE TITLE
[FR]: Add ability to tie jest version to a package.json file

### ISSUE THREAD

**Issue by Aghassi** [aspect-build/rules_jest#68]
### What is the current behavior?

This behavior exists in rules_ts and carrying it over would make rules_jest more use friendly.

Today, you have to select a version and it may drift from the package.json version

### Describe the feature

```
rules_ts_dependencies(ts_version_from = "//web/web-app/app:package.json")
```

Add the ability to inherit the jest version from a package.json so that we don't have to manage the workspace and the package.json

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by jbedard** [comment]
As of https://github.com/aspect-build/rules_jest/commit/696c9b2860acd7e5f8d3873ba88cbb2f6d5b1cce jest always comes from node_modules so this is no longer an issue, if I'm understanding correctly?

**Comment by Aghassi** [comment]
Yes you are correct, thanks for grooming. The newest versions solve this
