### ISSUE TITLE
[FR]: Support bzlmod

### ISSUE THREAD

**Issue by kyleconroy** [aspect-build/rules_jest#79]
### Describe the feature

I'm not sure if these rules support bzlmod. If they do, could you update the documentation with instructions on how to use it similar to [rules_js](https://github.com/aspect-build/rules_js/releases/tag/v1.13.0)?

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by gregmagolan** [comment]
@alexeagle @kormide The https://github.com/aspect-build/rules_jest/releases/tag/v0.17.0 release removes jest_repositories so this rule set should be easy to get onto bzlmod now.
