### ISSUE TITLE
[FR]: Support multiple nested __snapshot__ directories

### ISSUE THREAD

**Issue by Aghassi** [aspect-build/rules_jest#92]
### What is the current behavior?

Right now, the write_source_file underpinning the snapshot update command will take the first `__snapshot__` it finds and write that back. It will ignore any nested ones, requiring the end user to have multiple build files and other glue logic to make it work. On a small project, this is a lot of overhead.

### Describe the feature

```
❯ tree web/babel-preset
web/babel-preset
├── BUILD.bazel
├── README.md
├── __snapshots__
│   └── index.test.js.snap
├── deps.bzl
├── index.js
├── index.test.js
├── lazy-importer
│   ├── README.md
│   └── src
│       ├── __snapshots__
│       │   └── index.test.js.snap
│       ├── index.js
│       └── index.test.js
├── node_modules
│   └── @babel
│       ├── core -> ../.pnpm/@babel+core@7.18.6/node_modules/@babel/core
│       └── template -> ../.pnpm/@babel+template@7.18.6/node_modules/@babel/template
├── package.json
├── pnpm-lock.yaml
├── registerBabel.js
└── yarn.lock
```

I should be able to have one `jest_test` rule at the root `BUILD.bazel` file in this tree and it should write back to every folder that has a `__snapshot__` folder until such time I split out something and have another build file nested.

### Fund our work

- [ ] Sponsor our open source work by donating a [feature bounty](https://opencollective.com/aspect-build/)

**Comment by Aghassi** [comment]
Discussion for context https://bazelbuild.slack.com/archives/CEZUUKQ6P/p1674589681819949

**Comment by gregmagolan** [comment]
This is now supported.
